// @ts-check
import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import mdx from '@astrojs/mdx';
import tailwind from '@astrojs/tailwind';
import vercel from '@astrojs/vercel';

// https://astro.build/config
export default defineConfig({
  site: 'https://cmdx.pl',
  adapter: vercel(),

  integrations: [
    tailwind(),
    mdx(),
    sitemap({
      // Exclude any admin or private pages if needed
      filter: (page) => !page.includes('/admin/'),

      // Optional: Add custom pages not generated by Astro
      // customPages: ['https://cmdx.pl/external-page'],

      // Set global metadata for all pages
      changefreq: 'weekly',
      priority: 0.7,

      // Customize per-page metadata if needed
      serialize(item) {
        // Increase priority for homepage
        if (item.url === 'https://cmdx.pl/') {
          item.priority = 1.0;
          item.changefreq = 'daily';
        }

        // Increase priority for blog posts
        if (item.url.includes('/blog/')) {
          item.priority = 0.9;
          item.changefreq = 'monthly';
        }

        // Set last modified date
        item.lastmod = new Date();

        return item;
      },

      // Reduce file size by excluding unused namespaces
      namespaces: {
        news: false,
        video: false,
        image: false,
        xhtml: true, // Keep for multi-language support if needed
      },
    }),
  ],
});